describe('Home Page Spec', () => {
    it('check some necessary text', () => {
        cy.visit('/nid-pub')
        // cy.get('[id = "menu-button"]').click()
        // cy.contains(/English/i).click()
        cy.contains(/Bangladesh NID Application System/i).should('be.visible')
        cy.contains(/আপনার যদি জাতীয় পরিচয়পত্র থাকে, তাহলে আপনি রেজিস্টার করতে পারেন/i).should('be.visible')
        cy.contains(/আপনার জাতীয় পরিচয়পত্র না থাকলে আপনি নতুন নিবন্ধন করতে পারেন/i).should('be.visible')
        cy.contains(/আপনার যদি অনলাইন একাউন্ট থাকে তাহলে এখান থেকে লগইন করুন/i).should('be.visible')
        cy.contains(/যারা জাতীয় পরিচয়পত্র পেয়েছেন তারা সংশোধন \/ ডুপ্লিকেট কপির জন্য আবেদন করতে পারবেন, যাদের জাতীয় পরিচয়পত্র নেই তারা নতুন নিবন্ধনের জন্য আবেদন করতে পারবেন/i).should('be.visible')
        cy.contains(/ই-মেইলঃ info@nidw.gov.bd/i).should('be.visible')
        cy.contains(/হেল্পলাইনঃ ১০৫, \+৮৮ ০১৭০৮-৫০১২৬১ যোগাযোগের সময়ঃ রবিবার-বৃহস্পতিবার, সকাল ৯:০০টা - বিকাল ৫:০০টা পর্যন্ত।/i).should('be.visible')
        cy.contains(/সাধারন নির্দেশনাবলী/i).should('be.visible')
        cy.contains(/জাতীয় পরিচয়পত্র সংশোধন সংক্রান্ত জিজ্ঞাসা/i).should('be.visible')
        cy.contains(/জাতীয় পরিচয়পত্র হারিয়ে গেলে করণীয়/i).should('be.visible')
        cy.contains(/জাতীয় পরিচয়পত্র ও নিবন্ধন সংক্রান্ত জিজ্ঞাসা/i).should('be.visible')
        cy.get('a[href="/nid-pub/claim-account"]').should('exist')
        cy.get('a[href="/nid-pub/register-account"]').should('exist')
        cy.get('a[href="/nid-pub/feedback"]').should('exist')
    })
})